import UserInitializer from '@/components/UserInitializer'
import ReduxProvider from '@/store/ReduxProvider'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SkyPro Music',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReduxProvider>
      <html lang="ru" className={montserrat.variable}>
        <body>
          <UserInitializer />
          {children}
        </body>
      </html>
    </ReduxProvider>
  )
}
